Use pip install . now

diff --git a/install-snpy b/install-snpy
--- a/install-snpy
+++ b/install-snpy
@@ -105,10 +105,20 @@ else
       conda activate $location
    fi
 
+   # We still need pip to install SNooPy from source, so check it
+   PIP=$(which pip 2> /dev/null)
+   if [ $? -ne 0 ] ; then
+      echo "Installing PIP..."
+      conda install -y pip > pip.log 2>&1 || (echo "Installation of PIP failed. Check pip.log. Abort!"; exit)
+      PIP=$(which pip 2> /dev/null)
+      rm pip.log
+   fi
+
    # Now we have activated the environment, install the software
    for package in $mandatory_packages ; do
       echo "Installing ${package}..."
-      conda install -y $package > ${package}.log 2>&1 || (echo "Installation of $package failed. Abort!"; exit)
+      conda install -y $package > ${package}.log 2>&1 || (echo "Installation of $package failed. Check ${package}.log. Abort!"; exit)
+      rm ${package}.log
    done
 
    for package in $optional_packages ; do
@@ -116,7 +126,9 @@ else
       conda install -y $package > ${package}.log 2>&1
       if [ $? -ne 0 ] ; then
          echo "Trying PIP..."
-         pip install $package > ${package}.log 2>&1 || echo "Installation of optional package $package failed"
+         pip install $package > ${package}.log 2>&1 || echo "Installation of optional package $package failed. Check ${package}.log"
+      else
+         rm ${package}.log
       fi
    done
 
@@ -132,7 +144,7 @@ if [ $? -ne 0 ] ; then
 fi
 
 cd snpy
-python setup.py install > snpy.log 2>&1
+$PIP install . > snpy.log 2>&1
 echo "Done!  With any luck, SNooPy has been successfully installed into the"
 echo "virtual environment ${location}. From now on, if you want to run"
 echo "SNooPy, you will need to activate this virtual environment first. Then"
